api:
  auth_token: CIRCLECI_API_TOKEN
runner:
  name: CIRCLECI_RUNNER_NAME
  resource_class: circleci-runner/le-test
  command_prefix: ["/opt/circleci/launch-task"]
  working_directory: /opt/circleci/workdir/%s
  cleanup_working_directory: true
