version: 2.1

workflows:
  launch-agent:
    jobs:
      - launch-agent-test
      - launch-agent-build-and-publish:
          requires:
            - launch-agent-test
          filters:
            branches:
              only: main
          context: runner-publishing

jobs:
  launch-agent-test:
    docker:
      - image: cibuilds/docker:19.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build Dockerfiles"
          working_directory: ./launch-agent
          command: |
            docker build --file Dockerfile -t circleci/runner:launch-agent .

  launch-agent-build-and-publish:
    docker:
      - image: cibuilds/docker:19.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build & Tag Images"
          working_directory: ./launch-agent
          command: |
            docker build --file Dockerfile -t circleci/runner:launch-agent .
      - deploy:
          name: "Publish Docker Image"
          command: |
            echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
            docker push circleci/runner:launch-agent
      - run:
          name: "Publish Docker Hub Description"
          command: |
            # Update the Docker Hub description
            STUBB_VER=0.2.0
            STUBB_URL="https://github.com/CircleCI-Public/stubb/releases/download/v${STUBB_VER}/stubb_${STUBB_VER}-linux-amd64.tar.gz"
            curl -sSL $STUBB_URL | tar -xz -C /usr/local/bin stubb

            DOCKER_PASS=$DOCKER_TOKEN stubb set description circleci/runner ./README.md
